// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=js"
// @generated from file tank/search/v1/search.proto (package tank.search.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message as Message$1 } from "../../message/v1/message_pb.js";
import { file_tank_message_v1_message } from "../../message/v1/message_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tank/search/v1/search.proto.
 */
export const file_tank_search_v1_search: GenFile = /*@__PURE__*/
  fileDesc("Cht0YW5rL3NlYXJjaC92MS9zZWFyY2gucHJvdG8SDnRhbmsuc2VhcmNoLnYxIr0BCg1TZWFyY2hGaWx0ZXJzEhUKDWZyb21fdXNlcl9pZHMYASADKAkSFgoOaW5fY2hhbm5lbF9pZHMYAiADKAkSJgoDaGFzGAMgAygOMhkudGFuay5zZWFyY2gudjEuSGFzRmlsdGVyEioKBmJlZm9yZRgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKQoFYWZ0ZXIYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIo4BCg1TZWFyY2hSZXF1ZXN0EhQKDHdvcmtzcGFjZV9pZBgBIAEoCRINCgVxdWVyeRgCIAEoCRIuCgdmaWx0ZXJzGAMgASgLMh0udGFuay5zZWFyY2gudjEuU2VhcmNoRmlsdGVycxIOCgZjdXJzb3IYBCABKAkSDQoFbGltaXQYBSABKAUSCQoBcRgGIAEoCSJtCglTZWFyY2hIaXQSKQoHbWVzc2FnZRgBIAEoCzIYLnRhbmsubWVzc2FnZS52MS5NZXNzYWdlEhIKCmNoYW5uZWxfaWQYAiABKAkSEgoKaGlnaGxpZ2h0cxgDIAMoCRINCgVzY29yZRgEIAEoASKzAQoOU2VhcmNoUmVzcG9uc2USJwoEaGl0cxgBIAMoCzIZLnRhbmsuc2VhcmNoLnYxLlNlYXJjaEhpdBITCgtuZXh0X2N1cnNvchgCIAEoCRIWCg50b3RhbF9lc3RpbWF0ZRgDIAEoAxI1Cg5wYXJzZWRfZmlsdGVycxgEIAEoCzIdLnRhbmsuc2VhcmNoLnYxLlNlYXJjaEZpbHRlcnMSFAoMcGFyc2VkX3F1ZXJ5GAUgASgJKoQBCglIYXNGaWx0ZXISGgoWSEFTX0ZJTFRFUl9VTlNQRUNJRklFRBAAEhQKEEhBU19GSUxURVJfRklMRVMQARIUChBIQVNfRklMVEVSX0xJTktTEAISGAoUSEFTX0ZJTFRFUl9SRUFDVElPTlMQAxIVChFIQVNfRklMVEVSX0JMT0NLUxAEMlgKDVNlYXJjaFNlcnZpY2USRwoGU2VhcmNoEh0udGFuay5zZWFyY2gudjEuU2VhcmNoUmVxdWVzdBoeLnRhbmsuc2VhcmNoLnYxLlNlYXJjaFJlc3BvbnNlQtABChJjb20udGFuay5zZWFyY2gudjFCC1NlYXJjaFByb3RvUAFaU2dpdGh1Yi5jb20vdGFjdGljYWwtYWdlbnQtbmV1cmFsLWtub3dsZWRnZS9jb250cmFjdHMvZ2VuL2dvL3Rhbmsvc2VhcmNoL3YxO3NlYXJjaHYxogIDVFNYqgIOVGFuay5TZWFyY2guVjHKAg5UYW5rXFNlYXJjaFxWMeICGlRhbmtcU2VhcmNoXFYxXEdQQk1ldGFkYXRh6gIQVGFuazo6U2VhcmNoOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp, file_tank_message_v1_message]);

/**
 * @generated from message tank.search.v1.SearchFilters
 */
export type SearchFilters = Message<"tank.search.v1.SearchFilters"> & {
  /**
   * @generated from field: repeated string from_user_ids = 1;
   */
  fromUserIds: string[];

  /**
   * @generated from field: repeated string in_channel_ids = 2;
   */
  inChannelIds: string[];

  /**
   * @generated from field: repeated tank.search.v1.HasFilter has = 3;
   */
  has: HasFilter[];

  /**
   * @generated from field: google.protobuf.Timestamp before = 4;
   */
  before?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp after = 5;
   */
  after?: Timestamp;
};

/**
 * Describes the message tank.search.v1.SearchFilters.
 * Use `create(SearchFiltersSchema)` to create a new message.
 */
export const SearchFiltersSchema: GenMessage<SearchFilters> = /*@__PURE__*/
  messageDesc(file_tank_search_v1_search, 0);

/**
 * @generated from message tank.search.v1.SearchRequest
 */
export type SearchRequest = Message<"tank.search.v1.SearchRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * Free-text terms (websearch syntax: quoted phrases, -exclusions, OR).
   *
   * @generated from field: string query = 2;
   */
  query: string;

  /**
   * @generated from field: tank.search.v1.SearchFilters filters = 3;
   */
  filters?: SearchFilters;

  /**
   * @generated from field: string cursor = 4;
   */
  cursor: string;

  /**
   * @generated from field: int32 limit = 5;
   */
  limit: number;

  /**
   * Raw query with modifiers, parsed server-side and merged into query +
   * filters: `from:@name in:#tread has:file before:2026-09-01 after:2026-01-01`.
   *
   * @generated from field: string q = 6;
   */
  q: string;
};

/**
 * Describes the message tank.search.v1.SearchRequest.
 * Use `create(SearchRequestSchema)` to create a new message.
 */
export const SearchRequestSchema: GenMessage<SearchRequest> = /*@__PURE__*/
  messageDesc(file_tank_search_v1_search, 1);

/**
 * @generated from message tank.search.v1.SearchHit
 */
export type SearchHit = Message<"tank.search.v1.SearchHit"> & {
  /**
   * @generated from field: tank.message.v1.Message message = 1;
   */
  message?: Message$1;

  /**
   * @generated from field: string channel_id = 2;
   */
  channelId: string;

  /**
   * Plain-text fragments around the matched terms; no markup.
   *
   * @generated from field: repeated string highlights = 3;
   */
  highlights: string[];

  /**
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message tank.search.v1.SearchHit.
 * Use `create(SearchHitSchema)` to create a new message.
 */
export const SearchHitSchema: GenMessage<SearchHit> = /*@__PURE__*/
  messageDesc(file_tank_search_v1_search, 2);

/**
 * @generated from message tank.search.v1.SearchResponse
 */
export type SearchResponse = Message<"tank.search.v1.SearchResponse"> & {
  /**
   * @generated from field: repeated tank.search.v1.SearchHit hits = 1;
   */
  hits: SearchHit[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: int64 total_estimate = 3;
   */
  totalEstimate: bigint;

  /**
   * What the server understood from `q` (ids resolved) merged with `filters`.
   *
   * @generated from field: tank.search.v1.SearchFilters parsed_filters = 4;
   */
  parsedFilters?: SearchFilters;

  /**
   * The free-text remainder of `q` merged with `query`.
   *
   * @generated from field: string parsed_query = 5;
   */
  parsedQuery: string;
};

/**
 * Describes the message tank.search.v1.SearchResponse.
 * Use `create(SearchResponseSchema)` to create a new message.
 */
export const SearchResponseSchema: GenMessage<SearchResponse> = /*@__PURE__*/
  messageDesc(file_tank_search_v1_search, 3);

/**
 * @generated from enum tank.search.v1.HasFilter
 */
export enum HasFilter {
  /**
   * @generated from enum value: HAS_FILTER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: HAS_FILTER_FILES = 1;
   */
  FILES = 1,

  /**
   * @generated from enum value: HAS_FILTER_LINKS = 2;
   */
  LINKS = 2,

  /**
   * @generated from enum value: HAS_FILTER_REACTIONS = 3;
   */
  REACTIONS = 3,

  /**
   * @generated from enum value: HAS_FILTER_BLOCKS = 4;
   */
  BLOCKS = 4,
}

/**
 * Describes the enum tank.search.v1.HasFilter.
 */
export const HasFilterSchema: GenEnum<HasFilter> = /*@__PURE__*/
  enumDesc(file_tank_search_v1_search, 0);

/**
 * @generated from service tank.search.v1.SearchService
 */
export const SearchService: GenService<{
  /**
   * @generated from rpc tank.search.v1.SearchService.Search
   */
  search: {
    methodKind: "unary";
    input: typeof SearchRequestSchema;
    output: typeof SearchResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tank_search_v1_search, 0);

